# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  ort-nightly-index: # Define access for a private registry
    type: python-index
    url: https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/pypi/simple/
    replaces-base: true
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/requirements/ci/" # Location of package manifests
    schedule:
      interval: "daily"
    # disable version updates for pip dependencies
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/requirements/lintrunner/" # Location of package manifests
    schedule:
      interval: "weekly"
    # disable version updates for pip dependencies
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    # Update ort-nightly
    directory: "/requirements/ci/"
    registries:
      - ort-nightly-index
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
