# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python310-onnx:
      python.version: '3.10'
      onnx.standard: '1'
    Python39-onnx:
      python.version: '3.9'
      onnx.standard: '1'
    Python39-expe:
      python.version: '3.9'
      onnx.standard: '0'
    Python38-expe:
      python.version: '3.8'
      onnx.standard: '0'
    Python37-expe:
      python.version: '3.7'
      onnx.standard: '0'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements-dev.txt
  displayName: 'Install dependencies'

- script: |
      if [ '$(onnx.standard)' == '1' ]
        then
          pip uninstall -y onnx-function-experiment
          pip uninstall -y ort-function-experiment-nightly
          pip install onnx onnxruntime
      fi
  displayName: 'Install onnx'

- script: |
    python setup.py sdist
  displayName: 'package'

- script: |
    pytest -v onnxscript --cov=onnxscript --cov-report term-missing
  displayName: 'pytest'

- script: |
    python -m flake8 onnxscript --max-line-length 95 --exclude "**test/models/*.py,**onnx_backend_test_code/*.py"
  displayName: 'flake8'

- script: |
    python -m sphinx docs dist/html
  displayName: 'documentation'
