# Build the release version of the package and publish to artifacts

trigger: none

pool:
  vmImage: ubuntu-latest
variables:
  # Set the release environment variable to build a release version of the wheel
  ONNX_SCRIPT_RELEASE: 1
steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'
    displayName: 'Set Up Python'
  - script: python -m pip install --upgrade pip build wheel
    displayName: "Install Python build dependencies"
  - script: sed -i 's/name = "onnxscript"/name = "onnxscript-preview"/' 'pyproject.toml'
    displayName: 'Temporarily rename package to onnx-preview'
  - script: python -m build
    displayName: 'Build ONNX Script wheel'
  - task: CopyFiles@2
    displayName: 'Copy Python Wheel to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: 'dist'
      Contents: '*.whl'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  # - task: PublishBuildArtifacts@1
  #   displayName: 'Publish onnxscript'
  #   inputs:
  #     ArtifactName: onnxscript

  # Test the wheels. This needs to happen after PublishBuildArtifacts
  # to avoid interference with the artifacts
  - script: python -m pip install -r requirements-dev.txt
    displayName: 'Install Python dependencies'
  - script: python -m pip install dist/*.whl --no-deps
    displayName: 'Install wheel'
  - script: python -m pytest -v -n auto 
    displayName: 'Run tests'
