name: CI

on:
  push:
    branches:
      - main
      - 'gh/**/base' # ghstack base branches
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        name:
          - python311-onnx
          - python310-onnx
          - python39-onnx
          - python39-expe
          - python38-expe
          - python37-expe
        include:
          - name: python311-onnx
            python-version: "3.11"
            onnx_standard: true
            test_examples: true
          - name: python310-onnx
            python-version: "3.10"
            onnx_standard: true
            test_examples: true
          - name: python39-onnx
            python-version: "3.9"
            onnx_standard: true
            test_examples: false
          - name: python39-expe
            python-version: "3.9"
            onnx_standard: false
            test_examples: false
          - name: python38-expe
            python-version: "3.8"
            onnx_standard: false
            test_examples: false
          - name: python37-expe
            python-version: "3.7"
            onnx_standard: false
            test_examples: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: "**/requirements-dev.txt"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel build
          python -m pip install -r requirements-dev.txt

      - name: Install standard onnx
        if: ${{ matrix.onnx_standard }}
        run: |
          python -m pip uninstall -y onnx-function-experiment
          python -m pip uninstall -y ort-function-experiment-nightly
          python -m pip install onnx onnxruntime

      - name: Versions
        run: |
          pip list | grep numpy
          pip list | grep onnx
          pip list | grep torch

      - name: pytest
        run: pytest -v onnxscript --cov=onnxscript --cov-report=xml -n auto

      - name: Install package
        run: pip install .

      - name: Test examples
        if: ${{ matrix.test_examples }}
        run: pytest -v docs/test

      - name: Build package
        run: python -m build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  build_docs:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: "**/requirements-dev.txt"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements-dev.txt
      - name: Versions
        run: |
          pip list | grep numpy
          pip list | grep onnx
          pip list | grep torch
      - name: Install package
        run: pip install .
      - name: Build documentation
        run: python -m sphinx docs dist/html
