name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        name: [python310-onnx, python39-onnx, python39-expe, python38-expe, python37-expe]
        include:
          - name: python310-onnx
            python-version: "3.10"
            onnx_standard: true
            onnx_exp: false
            test_examples: true
          - name: python39-onnx
            python-version: "3.9"
            onnx_standard: true
            onnx_exp: false
            test_examples: false
          - name: python39-expe
            python-version: "3.9"
            onnx_standard: false
            onnx_exp: true
            test_examples: false
          - name: python38-expe
            python-version: "3.8"
            onnx_standard: false
            onnx_exp: true
            test_examples: false
          - name: python37-expe
            python-version: "3.7"
            onnx_standard: false
            onnx_exp: true
            test_examples: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.2.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: "**/requirements-dev.txt"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements-dev.txt

      - name: Install standard onnx
        if: ${{ matrix.onnx_standard }}
        run: |
          python -m pip install onnx onnxruntime

      - name: Install experimental onnx
        if: ${{ matrix.onnx_exp }}
        run: |
          python -m pip install -r requirements-dev-experiment.txt

      - name: Make package
        run: python setup.py sdist

      - name: pytest
        run: pytest -v onnxscript --cov=onnxscript --cov-report=xml -n auto

      - name: Install package
        run: pip install .

      - name: Test examples
        if: ${{ matrix.test_examples }}
        run: pytest -v docs/test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Build documentation
        if: and(${{ matrix.test_examples }}, eq('${{ matrix.os }}', 'ubuntu-latest'))
        run: python -m sphinx docs dist/html > stdout_stderror.log 2>&1
      - name: Check whether previous build docs succeeded
        if: and(${{ matrix.test_examples }}, eq('${{ matrix.os }}', 'ubuntu-latest'))
        run: |
          cat stdout_stderror.log
          if grep -F "build succeeded" stdout_stderror.log
          then
            echo "Build succeeded."
          else
            echo "Build failed."
            exit 1
          fi


  build_docs:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: "**/requirements-dev.txt"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements-dev.txt
      - name: Install package
        run: pip install .
      - name: Build documentation
        run: python -m sphinx docs dist/html > stdout_stderror.log 2>&1
      - name: Check whether previous build docs succeeded
        run: |
          cat stdout_stderror.log
          if grep -F "build succeeded" stdout_stderror.log
          then
            echo "Build succeeded."
          else
            echo "Build failed."
            exit 1
          fi
